name: 'Triet Le'
description: 'Attempt to create a pull request and trigger a collection of actions (workflow) from another repo.'
author: 'Plus3 IT Systems'
inputs:
  github-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
